- id: muff-check
  name: muff check
  description: "Run 'muff check' for extremely fast Python linting"
  entry: muff check --force-exclude
  language: python
  types_or: [python, pyi, jupyter]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"

- id: muff-format
  name: muff format
  description: "Run 'muff format' for extremely fast Python formatting"
  entry: muff format --force-exclude
  language: python
  types_or: [python, pyi, jupyter]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"

# Legacy alias
- id: muff
  name: muff (legacy alias)
  description: "Run 'muff check' for extremely fast Python linting"
  entry: muff check --force-exclude
  language: python
  types_or: [python, pyi, jupyter]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
